---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ldaprbac.io
  resources:
  - clusterrbacgroupbindings
  - rbacgroupbindings
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ldaprbac.io
  resources:
  - clusterrbacgroupbindings/status
  - rbacgroupbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ldaprbac.io
  resources:
  - ldapproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
