{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "directory-rbac-operator.fullname" . }}
  labels:
    {{- include "directory-rbac-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "directory-rbac-operator.selectorLabels" . | nindent 6 }}
{{- end }}
